version: "3.3"
services:
  cryptboard-webapp:
    build:
      context: ../   
      dockerfile: ./docker/Dockerfile-webapp
    image: cryptboard-webapp:latest
    links:
      - redis
    env_file:
      - ../web-app/.env.docker

  redis:
    image: redis
    volumes:
      - ../redis-data:/data
    entrypoint: redis-server --appendonly yes

  nginx:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-nginx
    # используем последний стабильный образ nginx
    image: cryptboard-nginx:latest
    # маршрутизируем порты
    ports:
      - "${SERVER_PORT}:80"      
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ../conf/nginx/docker-nginx-conf.d:/etc/nginx/conf.d
    # nginx должен общаться с php контейнером
    links:
      - cryptboard-webapp

