version: "3.3"
services:
  cryptboard-webapp:
    build:
      context: ../   
      dockerfile: ./docker/Dockerfile-webapp
    image: cryptboard-webapp:tag
   
  redis:
    image: redis
    ports:
      - "26379:26379"
    volumes:
      - ../redis-data:/data
    entrypoint: redis-server --appendonly yes
    