name: deploy-main
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: bash -c "cd ~/cryptboard.io && git pull && cd ./web-app && export HOME=/home/cryptboard && composer install"

